"""initial_tables

Revision ID: 00a2cf052728
Revises: 
Create Date: 2026-06-01 14:27:49.019045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a2cf052728'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.Column('nombre_especialidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad')
    )
    op.create_index(op.f('ix_especialidad_id_especialidad'), 'especialidad', ['id_especialidad'], unique=False)
    op.create_table('estado_turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estado_turno_id'), 'estado_turno', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('mail')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=False),
    sa.Column('especialidad_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['especialidad_id'], ['especialidad.id_especialidad'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('mail')
    )
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.create_table('recomienda',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_medico_recomendado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_medico_recomendado'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id_medico', 'id_medico_recomendado')
    )
    op.create_table('resenas',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('estrellas', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    op.create_index(op.f('ix_resenas_id_resena'), 'resenas', ['id_resena'], unique=False)
    op.create_table('turno',
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('id_pacientes', sa.Integer(), nullable=False),
    sa.Column('id_medicos', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['estado_turno.id'], ),
    sa.ForeignKeyConstraint(['id_medicos'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_pacientes'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id_turno')
    )
    op.create_index(op.f('ix_turno_id_turno'), 'turno', ['id_turno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_id_turno'), table_name='turno')
    op.drop_table('turno')
    op.drop_index(op.f('ix_resenas_id_resena'), table_name='resenas')
    op.drop_table('resenas')
    op.drop_table('recomienda')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_estado_turno_id'), table_name='estado_turno')
    op.drop_table('estado_turno')
    op.drop_index(op.f('ix_especialidad_id_especialidad'), table_name='especialidad')
    op.drop_table('especialidad')
    # ### end Alembic commands ###
