"""horario_medico

Revision ID: df94d030364d
Revises: 0c77135e95c7
Create Date: 2026-08-12 15:15:17.663303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df94d030364d'
down_revision: Union[str, Sequence[str], None] = '0c77135e95c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horario_medico_id'), 'horario_medico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horario_medico_id'), table_name='horario_medico')
    op.drop_table('horario_medico')
    # ### end Alembic commands ###
